/*
 * WARNING: THIS FILE IS GENERATED AUTOMATICALLY.
 * DO NOT EDIT THIS FILE MANUALLY.
 * ALL CHANGES WILL BE LOST UPON REGENERATION.
 */

public enum Iide.IconID {
    FOLDER = 0,
    LS_CLASS = 1,
    LS_METHOD = 2,
    LS_FIELD = 3,
    LS_ENUM = 4,
    LS_INTERFACE = 5,
    LS_TEXT = 6,
    LS_CONSTRUCTOR = 7,
    LS_MODULE = 8,
    LS_KEYWORD = 9,
    LS_SNIPPET = 10,
    LS_COLOR = 11,
    LS_FILE = 12,
    LS_FOLDER = 13,
    LS_CONSTANT = 14,
    LS_STRUCT = 15,
    LS_OPERATOR = 16,
    LS_PROPERTY = 17,
    LS_ENUM_MEMBER = 18,
    LS_TYPE_PARAMETER = 19,
    LS_LITERAL = 20,
    LS_DEFAULT = 21,
    MT_XML = 22;
}

public class Iide.SymbIconProvider {
    private static SymbIconProvider? instance = null;
    public static SymbIconProvider get_instance () {
        if (instance == null) {
            instance = new SymbIconProvider ();
        }
        return instance;
    }

    private string[,] _icon_indexes;
    private string _prefix = "def-";

    private SymbIconProvider () {
        _icon_indexes = {
            { "folder", "folder" },
            { "ls-class", "ls-class" },
            { "ls-method", "ls-method" },
            { "ls-field", "ls-field" },
            { "ls-enum", "ls-class" },
            { "ls-interface", "ls-interface" },
            { "ls-text", "" },
            { "ls-constructor", "ls-constructor" },
            { "ls-module", "ls-module" },
            { "ls-keyword", "" },
            { "ls-snippet", "ls-snippet" },
            { "ls-color", "ls-color" },
            { "ls-file", "" },
            { "ls-folder", "ls-folder" },
            { "ls-constant", "" },
            { "ls-struct", "ls-struct" },
            { "ls-operator", "" },
            { "ls-property", "ls-property" },
            { "ls-enum-member", "ls-enum-member" },
            { "ls-type-parameter", "ls-type-parameter" },
            { "ls-literal", "ls-literal" },
            { "ls-default", "" },
            { "mt-xml", "" },
        };
    }
    public Gtk.Image image (IconID icon_id, bool colorize = true, int? pixel_size = null) {
        var icon_name = _icon_indexes[(int) icon_id, 0];
        Gtk.Image img = new Gtk.Image.from_icon_name (_prefix + icon_name + "-symbolic");
        if (colorize) {
            var class_name = _icon_indexes[(int) icon_id, 1];
            if (class_name.length > 0) {
                img.add_css_class (_prefix + class_name);
            }
        }
        if (pixel_size != null) {
            img.pixel_size = pixel_size;
        }
        return img;
    }
}
