#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
#   "pygobject",
#   "pycairo",
# ]
# ///

from pathlib import Path
import os, json, sys, shutil, cairo, gi

gi.require_version('Pango', '1.0')
gi.require_version('PangoCairo', '1.0')

from gi.repository import Pango, PangoCairo


def export_glyph(symbol, font_desc, output_dir, icon_name):
    filename = os.path.join(output_dir, f"{icon_name}-symbolic.svg")
    surface = cairo.SVGSurface(filename, 256, 256)
    cr = cairo.Context(surface)
    layout = PangoCairo.create_layout(cr)
    layout.set_text(symbol, -1)
    layout.set_font_description(Pango.FontDescription.from_string(font_desc))
    
    ink, _ = layout.get_extents()
    w, h = ink.width/Pango.SCALE, ink.height/Pango.SCALE
    scale = (256 * 0.84) / max(w, h)
    
    cr.translate(128 - (w*scale/2) - (ink.x*scale/Pango.SCALE),
                 128 - (h*scale/2) - (ink.y*scale/Pango.SCALE))
    cr.scale(scale, scale)
    PangoCairo.layout_path(cr, layout)
    cr.set_source_rgba(0.745, 0.745, 0.745, 1.0)
    cr.fill()
    surface.finish()

    with open(filename, 'r') as f: content = f.read()
    with open(filename, 'w') as f:
        f.write(content.replace("rgb(74.509804%, 74.509804%, 74.509804%)", "currentColor")
                .replace("</svg>", "<style>.symbolic { fill: currentColor; }</style></svg>"))


generated_warning = [
    "/*",
    " * WARNING: THIS FILE IS GENERATED AUTOMATICALLY.",
    " * DO NOT EDIT THIS FILE MANUALLY.",
    " * ALL CHANGES WILL BE LOST UPON REGENERATION.",
    " */",
    ""
]


def generate_provider_source_file(icon_names):
    src_path = Path(__file__).parent.parent / 'src' / 'Services' / 'SymbIconProvider.vala'
    with src_path.open('wt', encoding='utf-8') as f:
        f.writelines("\n".join(generated_warning))

        # Iide.IconID
        f.write('\npublic enum Iide.IconID {\n')
        enums = [f"    {iid[0]} = {i}" for i, iid in enumerate(icon_names)]
        f.write(",\n".join(enums) + ";\n}\n\n")

        # Iide.SymbIconProvider
        f.writelines([
            'public class Iide.SymbIconProvider {\n',
            '    private static SymbIconProvider? instance = null;\n',
            '    public static SymbIconProvider get_instance () {\n',
            '        if (instance == null) {\n',
            '            instance = new SymbIconProvider ();\n',
            '        }\n',
            '        return instance;\n',
            '    }\n'
            '\n',
            '    private string[,] _icon_indexes;\n',
            '    private string _prefix = "def-";\n',
            '\n',
            '    private SymbIconProvider () {\n',
            '        _icon_indexes = {\n',
        ])
        for iid in icon_names:
            f.write(f'            {{ "{iid[1]}", "{iid[2]}" }},\n')
        f.writelines([
            '        };\n',
            '    }\n',
            '    public Gtk.Image image (IconID icon_id, bool colorize = true, int? pixel_size = null) {\n',
            '        var icon_name = _icon_indexes[(int) icon_id, 0];\n',
            '        Gtk.Image img = new Gtk.Image.from_icon_name (_prefix + icon_name + "-symbolic");\n',
            '        if (colorize) {\n',
            '            var class_name = _icon_indexes[(int) icon_id, 1];\n',
            '            if (class_name.length > 0) {\n',
            '                img.add_css_class (_prefix + class_name);\n',
            '            }\n',
            '        }\n',
            '        if (pixel_size != null) {\n',
            '            img.pixel_size = pixel_size;\n',
            '        }\n',
            '        return img;\n',
            '    }\n',
            '}\n'
        ])



def main():
    # Проверка аргументов (Meson передает их в строго определенном порядке)
    if len(sys.argv) < 5:
        print("Usage: export_glyph.py <json> <ttf> <out_base> <xml_path>")
        sys.exit(1)

    _, json_path, ttf_path, out_base, xml_output_path = sys.argv
    
    # Регистрация шрифта через переменные окружения (безопасно для Arch/TypeLib)
    font_dir = os.path.dirname(os.path.abspath(ttf_path))
    os.environ["Pango_FONT_PATH"] = font_dir
    
    with open(json_path, 'r') as f:
        config = json.load(f)

    prefix = config.get("prefix", "def-")
    font_family = config.get("font_name", "Sans")
    styles_data = config.get("styles", {})
    icons_data = config.get("icons", {})

    # Подготовка путей: очищаем старое, создаем структуру для SVG
    actions_dir = os.path.join(out_base, "scalable", "actions")
    if os.path.exists(out_base):
        shutil.rmtree(out_base)
    os.makedirs(actions_dir)

    icon_names = []

    styles = {style_name: colors for style_name, colors in styles_data.items()}
    icon_indexes = []

    # Итерируемся по иконкам из JSON
    for name, data in icons_data.items():
        # Поддержка расширенного и сокращенного форматов в JSON
        style_name = ""
        if isinstance(data, dict):
            char_raw = data.get("char")
            style_name = data.get("style")
            if style_name not in styles:
                style_name = ""
        else:
            char_raw = data
        
        full_name = f"{prefix}{name}"
        icon_indexes.append(
            [
                name.replace("-", "_").upper(), # IconID
                f"{name}",                      # (def-)icon-name(-symbolic)
                style_name,                     # css-class-name
            ]
        )
        
        # Парсим HEX-коды (0x... или U+...)
        if isinstance(char_raw, str) and char_raw.lower().startswith(("0x", "u+")):
            char_parsed = chr(int(char_raw.lower().replace("u+", "").replace("0x", ""), 16))
        else:
            char_parsed = str(char_raw)
        
        # 1. Генерируем SVG файл
        # Передаем размер шрифта (например, 200), чтобы Pango отрисовал четкий контур
        export_glyph(char_parsed, f"{font_family} 200", actions_dir, full_name)
        icon_names.append(full_name)
    
    # Сохраняем сгенерированный CSS
    cwd = os.path.dirname(__file__)
    css_file_name = "symbols.css"
    with open(os.path.join(cwd, "symbols.css"), 'w') as f:
        f.write("\n".join(generated_warning))
        for style_name, colors in styles.items():
            f.write(f".{prefix}{style_name} {{ color: {colors[0]}; }}\n")
            f.write(f".dark .{prefix}{style_name} {{ color: {colors[1]}; }}\n\n")

    # Создаем итоговый XML файл ресурсов для GLib
    with open(xml_output_path, 'w') as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n<gresources>\n')
        # Префикс ресурса, по которому Vala будет искать иконки и стили
        f.write('  <gresource prefix="/org/github/kai66673/iide/symbols">\n')
        f.write(f'    <file alias="{css_file_name}">{css_file_name}</file>\n')
        f.write('  </gresource>\n')
        f.write('  <gresource prefix="/org/github/kai66673/iide/icons">\n')
        for n in icon_names:
            f.write(f'    <file>scalable/actions/{n}-symbolic.svg</file>\n')
        f.write('  </gresource>\n</gresources>')

    # Generate SymbIconProvider.vala
    generate_provider_source_file(icon_indexes)
    
    print(f"Successfully generated {len(icon_names)} icons and {css_file_name}")


if __name__ == "__main__":
    main()
